### PR TITLE
Make sure to build fix in #9 and update index.js

### PR DESCRIPTION
**Pull request by fossamagna**
build fix in https://github.com/StafflinePeoplePlus/dependabot-changesets/pull/9 and update index.js

refs #8

### CODE REVIEW

**Comment by wobsoriano** [comment]
Can we test this in a PR or something?

**Comment by fossamagna** [comment]
@jamesbirtles I would be grateful if you could review it.

**Comment by jamesbirtles** [comment]
Unfortunately you caught me right at the end of my employment with PeoplePlus, which has now ended, so I don't have the authority to merge this any more

**Comment by wobsoriano** [comment]
@jamesbirtles Thanks for the update. Wishing you the best in your future role. Would it be okay to fork the repo, or is there someone else we can contact about merging this PR?

**Comment by jamesbirtles** [comment]
@mashaibani might be able to help, otherwise its MIT licensed so forking is no problem

**Pull request merged**
